<?php
/**
 * @file
 * Code for the OlpConfigs feature.
 */

include_once('olpconfigs.features.inc');

function olpconfigs_install() {
  olpconfigs_config_blocks();
}

function olpconfigs_config_blocks() {  
  //disable navigation block
  $bQuery = db_update('block'); 
  $bQuery->fields(array('status' => 0, 'region' => -1));  
  $bQuery->condition('module', 'system');
  $bQuery->condition('delta', 'navigation');
  $bQuery->condition('theme', 'omega');
  $bQuery->execute();

  //disable search block
  $bQuery = db_update('block'); 
  $bQuery->fields(array('status' => 0, 'region' => -1));  
  $bQuery->condition('module', 'search');
  $bQuery->condition('delta', 'form');
  $bQuery->condition('theme', 'omega');
  $bQuery->execute();    
}